# Generated by Django 4.1 on 2022-08-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_alter_balances_id_alter_getdata_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Emp',
        ),
    ]
